# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_content_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content_2',
            name='author',
        ),
        migrations.DeleteModel(
            name='Content_2',
        ),
    ]
