# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_menu_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_one',
            name='html_one',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='menu_one',
            name='item_one',
            field=models.CharField(max_length=10),
        ),
    ]
