# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_auto_20171118_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cont_start',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont_start_1', models.CharField(max_length=100, null=True)),
                ('cont_start_2', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
