# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_auto_20171119_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='start_sec',
            old_name='start_text_one',
            new_name='text_sec_one',
        ),
    ]
