# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0012_auto_20171119_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info_sec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_comp', models.CharField(max_length=20, null=True)),
                ('info_comp_text', models.TextField()),
                ('info_conc', models.CharField(max_length=20, null=True)),
                ('info_conc_text', models.TextField()),
                ('info_param', models.CharField(max_length=20, null=True)),
                ('info_param_text', models.TextField()),
                ('info_qual', models.CharField(max_length=20, null=True)),
                ('info_qual_text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Start_sec',
        ),
    ]
