# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0013_auto_20171121_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info_sec',
            old_name='info_comp',
            new_name='brief_part',
        ),
        migrations.RenameField(
            model_name='info_sec',
            old_name='info_comp_text',
            new_name='info_part',
        ),
        migrations.RemoveField(
            model_name='info_sec',
            name='info_conc',
        ),
        migrations.RemoveField(
            model_name='info_sec',
            name='info_conc_text',
        ),
        migrations.RemoveField(
            model_name='info_sec',
            name='info_param',
        ),
        migrations.RemoveField(
            model_name='info_sec',
            name='info_param_text',
        ),
        migrations.RemoveField(
            model_name='info_sec',
            name='info_qual',
        ),
        migrations.RemoveField(
            model_name='info_sec',
            name='info_qual_text',
        ),
    ]
