# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0014_auto_20171121_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_sec',
            name='url_part',
            field=models.URLField(max_length=20, null=True),
        ),
    ]
