# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0016_auto_20171121_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_sec',
            name='url_part',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
