# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0017_auto_20171121_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea_sec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_part', models.CharField(max_length=20, null=True)),
                ('text_part', models.TextField()),
                ('link_part', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
