# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0019_idea_sec_linkname_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content_en',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Idea_en',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_en', models.CharField(max_length=20, null=True)),
                ('text_en', models.TextField()),
                ('link_en', models.CharField(max_length=50, null=True)),
                ('linkname_en', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Info_en',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief_en', models.CharField(max_length=20, null=True)),
                ('info_en', models.TextField()),
                ('url_en', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu_en',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_en', models.CharField(max_length=10, null=True)),
                ('html_en', models.CharField(max_length=20, null=True)),
                ('fafa_en', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
