# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0020_content_en_idea_en_info_en_menu_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_one',
            name='item_en',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
