# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0021_menu_one_item_en'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content_en',
        ),
        migrations.DeleteModel(
            name='Menu_en',
        ),
        migrations.AddField(
            model_name='content_2',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='info_sec',
            name='brief_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='info_sec',
            name='info_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='content_2',
            name='text_2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='info_sec',
            name='info_part',
            field=models.TextField(null=True),
        ),
    ]
