# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0022_auto_20171202_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea_sec',
            name='linkname_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='idea_sec',
            name='offer_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='idea_sec',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='idea_sec',
            name='text_part',
            field=models.TextField(null=True),
        ),
    ]
