# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-30 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0023_auto_20171202_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='content_2',
            name='comment_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='content_2',
            name='comment_ru',
            field=models.TextField(null=True),
        ),
    ]
